version: '3'
services:
  cecmonitor:
    image: negativefusion/cecmonitor
    container_name: cecmonitor 
    build:
        context: ../projects/cecmonitor/
        dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - TV_IP_ADDRESS={TV_IP_ADDRESS}
      #- ADDITIONAL_ARGS=-v     #add additional command line arguments
    restart: unless-stopped
    volumes:
      - ./conf:/root/.android
